// gitprofile.config.ts

const CONFIG = {
  github: {
    username: 'anish-kumar1999',
  },
  base: '/',
  projects: {
    github: {
      display: true,
      header: 'GitHub Projects',
      mode: 'automatic',
      automatic: {
        sortBy: 'updated',
        limit: 10,
        exclude: {
          forks: false,
          projects: [],
        },
      },
      manual: {
        projects: [],
      },
    },
    external: {
      header: 'Featured Projects',
      projects: [
        {
          title: 'EduGenie Labs - LMS Platform',
          description: 'A fully-featured Laravel-based Learning Management System. I am responsible for system modifications, management, and enhancing the platform for instructors and students.',
          imageUrl: '',
          link: 'https://edugenielabs.com/',
        },
        {
          title: 'PMJ Retail - AI-Powered Store Management',
          description: 'An internal system for PMJ Jewels that leverages AI intelligence to manage store cameras and operations. I worked on the CRM and backend development for this platform.',
          imageUrl: '',
          link: 'https://retail.bcss.ai/admin',
        },
        {
          title: 'WedUnReal - Wedding Planning Platform',
          description: 'A comprehensive platform for booking hotel rooms, private charters, and connecting with wedding vendors like photographers, makeup artists, and decorators.',
          imageUrl: '',
          link: 'https://wedunreal.com/',
        },
        {
          title: 'Whizlabs - EdTech Platform',
          description: 'Contributed to this online learning platform, helping build and enhance features for a seamless educational experience.',
          imageUrl: '',
          link: 'https://www.whizlabs.com/',
        },
        {
          title: 'Nosho - E-commerce Platform',
          description: 'Worked on this e-commerce solution, focusing on backend integrations and performance optimization.',
          imageUrl: '',
          link: 'https://www.nosho.app/',
        },
        {
          title: 'Donatuz - Donation Platform',
          description: 'Contributed to the development of this donation platform, building and integrating core features.',
          imageUrl: '',
          link: 'https://www.donatuz.com/',
        },
        {
          title: 'DraughtGuardian - IoT Solution',
          description: 'Worked on this IoT project, integrating web technologies with hardware solutions for monitoring and management.',
          imageUrl: '',
          link: 'https://site.draughtguardian.com/',
        },
        {
          title: 'FashionMingle - Social Fashion Platform',
          description: 'Developed features for this social networking platform focused on fashion, connecting designers, brands, and enthusiasts.',
          imageUrl: '',
          link: 'https://fashionmingle.com/',
        },
        {
          title: 'HCFX - Foreign Exchange Portal',
          description: 'Foreign exchange portal built with WordPress, integrated with Salesforce for user onboarding and API-driven data synchronization.',
          imageUrl: '',
          link: '',
        },
        {
          title: 'Chartprime - Subscription Management',
          description: 'Integrated Chargebee subscription management with WordPress. Built custom subscription UI for plan and add-on management beyond default capabilities.',
          imageUrl: '',
          link: '',
        },
        {
          title: 'Nory - HubSpot UI Extension',
          description: 'Custom HubSpot UI Extension built with React. Serverless backend functions in Node.js within HubSpot\'s ecosystem for workflow automation.',
          imageUrl: '',
          link: '',
        },
        {
          title: 'Nordics NG - Serverless Onboarding',
          description: 'Serverless onboarding workflow using AWS Lambda triggered by Webflow webhooks. Automated customer creation, subscription setup across Chargebee and Norwegian banking systems.',
          imageUrl: '',
          link: '',
        },
        {
          title: 'RAG-Based Proposal Generation System',
          description: 'In-house RAG system leveraging LLMs, built with Python (FastAPI), Next.js, LangChain, OpenAI APIs, and vector databases including ChromaDB and OpenSearch.',
          imageUrl: '',
          link: '',
        },
        {
          title: 'RikaAmrit - Internal CRM',
          description: 'Developed and managed an internal CRM system for RikaAmrit to streamline business processes and customer management.',
          imageUrl: '',
          link: '',
        },
      ],
    },
  },
  seo: {
    title: 'Anish Kumar - Software Engineer II | Full-Stack Developer | SaaS Builder & AI Enthusiast',
    description: 'Software Engineer II at Blue Cloud Softech. Full-Stack Developer with 5+ years experience in PHP, Laravel, Node.js, React.js, Python, AI/LLM, and cloud integrations.',
    imageURL: '',
  },
  social: {
    linkedin: 'anish-kumar1999',
    x: '',
    mastodon: '',
    researchGate: '',
    facebook: '',
    instagram: '',
    reddit: '',
    threads: '',
    youtube: '',
    udemy: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '',
    stackoverflow: '',
    discord: '',
    telegram: '',
    website: '',
    phone: '+918054877087',
    email: 'akbhuria0786@gmail.com',
  },
  resume: {
    fileUrl: '', 
  },
  skills: [
    'PHP',
    'Laravel',
    'CodeIgniter',
    'Node.js',
    'Python',
    'FastAPI',
    'Core PHP',
    'REST APIs',
    'Webhooks',
    'Sequelize',
    'AWS Lambda',
    'Serverless Architecture',
    'HTML5',
    'CSS3',
    'JavaScript',
    'jQuery',
    'AJAX',
    'React.js',
    'Next.js',
    'Bootstrap',
    'Vue.js',
    'WordPress',
    'Shopify',
    'Webflow',
    'Headless CMS',
    'MySQL',
    'MongoDB',
    'VectorDB',
    'ChromaDB',
    'OpenSearch',
    'LLM',
    'LangChain',
    'RAG Systems',
    'OpenAI APIs',
    'HubSpot CRM',
    'HubSpot Developer',
    'GoHighLevel',
    'Salesforce',
    'Chargebee',
    'Stripe',
    'Payment Gateways',
    'AWS S3',
    'Cloudways',
    'DigitalOcean',
    'Hostinger',
    'GoDaddy',
    'Git',
    'GitHub',
    'Bitbucket',
  ],
  experiences: [
    {
      company: 'Blue Cloud Softech Solutions Limited',
      position: 'Software Engineer II',
      from: 'January 2026',
      to: 'Present',
      companyLink: 'https://www.bluecloudsoftech.com/',
    },
    {
      company: 'Freelance Full Stack Engineer',
      position: 'Full-Stack Developer & Consultant',
      from: 'August 2020',
      to: 'Present',
      companyLink: '',
    },
    {
      company: 'Techglock Software Solutions',
      position: 'Web Developer',
      from: 'November 2021',
      to: 'November 2025',
      companyLink: 'https://techglock.com',
    },
    {
      company: 'AMR Softec',
      position: 'PHP Web Developer',
      from: 'July 2021',
      to: 'October 2021',
      companyLink: '',
    },
    {
      company: 'AMR Softec',
      position: 'PHP Web Developer Intern',
      from: 'March 2021',
      to: 'June 2021',
      companyLink: '',
    },
  ],
  certifications: [],
  educations: [
    {
      institution: 'Chandigarh University',
      degree: 'Master of Computer Applications (MCA)',
      from: '2021',
      to: '2023',
    },
    {
      institution: 'Guru Nanak Dev University (GNDU)',
      degree: 'Bachelor of Computer Applications (BCA)',
      from: '2017',
      to: '2020',
    },
  ],
  publications: [],
  blog: {
    source: 'dev',
    username: '',
    limit: 2,
  },
  googleAnalytics: {
    id: '',
  },
  hotjar: { id: '', snippetVersion: 6 },
  themeConfig: {
    defaultTheme: 'dark',
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'caramellatte',
      'abyss',
      'silk',
      'procyon',
    ],
  },
  footer: `Made with <a 
      class="text-primary" href="https://anish-kumar1999.github.io/"
      target="_blank"
      rel="noreferrer"
    >GitProfile</a> and ❤️`,
  enablePWA: true,
};

export default CONFIG;
